import { TranslationMap } from "@typesDir/types";

export const ClothingColors: TranslationMap = {
  AliceBlue: "Алисин Синий",
  AntiqueWhite: "Антикварный Белый",
  Aqua: "Аква",
  Aquamarine: "Аквамарин",
  Azure: "Азурный",
  Beige: "Бежевый",
  Bisque: "Бисквитный",
  Black: "Чёрный",
  BlanchedAlmond: "Отбеленный Миндаль",
  Blue: "Синий",
  BlueViolet: "Синий Фиолетовый",
  Brown: "Коричневый",
  BurlyWood: "Бурый Лес",
  CadetBlue: "Кадетский Синий",
  Chartreuse: "Шартрез",
  Chocolate: "Шоколадный",
  Coral: "Коралл",
  CornflowerBlue: "Голубой Василёк",
  Cornsilk: "Кукурузный Шелк",
  Crimson: "Багряный",
  Cyan: "Циан",
  DarkBlue: "Тёмно-Синий",
  DarkCyan: "Тёмный Циан",
  DarkGoldenrod: "Тёмная Золотистая Рудка",
  DarkGray: "Тёмно-Серый",
  DarkGreen: "Тёмно-Зелёный",
  DarkKhaki: "Тёмный Хаки",
  DarkMagenta: "Тёмная Магента",
  DarkOliveGreen: "Тёмно-Оливковый Зелёный",
  DarkOrange: "Тёмно-Оранжевый",
  DarkOrchid: "Тёмная Орхидея",
  DarkRed: "Тёмно-Красный",
  DarkSalmon: "Тёмный Лосось",
  DarkSeaGreen: "Тёмно-Морской Зелёный",
  DarkSlateBlue: "Тёмный Сланцевый Синий",
  DarkSlateGray: "Тёмный Сланцевый Серый",
  DarkTurquoise: "Тёмный Бирюзовый",
  DarkViolet: "Тёмный Фиолетовый",
  DeepPink: "Глубокий Розовый",
  DeepSkyBlue: "Глубокий Небесный Синий",
  DimGray: "Тусклый Серый",
  DodgerBlue: "Синий Доджер",
  FireBrick: "Кирпичный Огонь",
  FloralWhite: "Цветочный Белый",
  ForestGreen: "Лесной Зелёный",
  Fuchsia: "Фуксия",
  Gainsboro: "Гейнсборо",
  GhostWhite: "Призрачный Белый",
  Gold: "Золотой",
  Goldenrod: "Золотистая Рудка",
  Gray: "Серый",
  Green: "Зелёный",
  GreenYellow: "Зелёный Жёлтый",
  Honeydew: "Мёд",
  HotPink: "Горячий Розовый",
  IndianRed: "Индийский Красный",
  Indigo: "Индиго",
  Ivory: "Слоновая Кость",
  Khaki: "Хаки",
  Lavender: "Лаванда",
  LavenderBlush: "Лавандовый Румянец",
  LawnGreen: "Лужайка Зелёная",
  LemonChiffon: "Лимонный Шифон",
  LightBlue: "Светло-Синий",
  LightCoral: "Светлый Коралл",
  LightCyan: "Светлый Циан",
  LightGoldenrodYellow: "Светло-Золотистый Жёлтый",
  LightGreen: "Светло-Зелёный",
  LightGrey: "Светло-Серый",
  LightPink: "Светлый Розовый",
  LightSalmon: "Светлый Лосось",
  LightSeaGreen: "Светлый Морской Зелёный",
  LightSkyBlue: "Светлый Небесный Синий",
  LightSlateGray: "Светлый Сланцевый Серый",
  LightSteelBlue: "Светлый Стальной Синий",
  LightYellow: "Светло-Жёлтый",
  Lime: "Лайм",
  LimeGreen: "Зелёный Лайм",
  Linen: "Льняной",
  Magenta: "Магента",
  Maroon: "Бордовый",
  MediumAquaMarine: "Средний Аквамарин",
  MediumBlue: "Средний Синий",
  MediumOrchid: "Средняя Орхидея",
  MediumPurple: "Средний Фиолетовый",
  MediumSeaGreen: "Средний Морской Зелёный",
  MediumSlateBlue: "Средний Сланцевый Синий",
  MediumSpringGreen: "Средний Весенний Зелёный",
  MediumTurquoise: "Средний Бирюзовый",
  MediumVioletRed: "Средний Вишнёво-Красный",
  MidnightBlue: "Полуночный Синий",
  MintCream: "Мятный Крем",
  MistyRose: "Туманный Розовый",
  Moccasin: "Мокасин",
  NavajoWhite: "Навахо Белый",
  Navy: "Морской",
  OldLace: "Старое Кружево",
  Olive: "Оливковый",
  OliveDrab: "Оливковая Тёмная",
  Orange: "Оранжевый",
  OrangeRed: "Оранжево-Красный",
  Orchid: "Орхидея",
  PaleGoldenrod: "Бледно-Золотистая Рудка",
  PaleGreen: "Бледно-Зелёный",
  PaleTurquoise: "Бледный Бирюзовый",
  PaleVioletRed: "Бледный Вишнёво-Красный",
  PapayaWhip: "Папайя Вип",
  PeachPuff: "Персиковый Пух",
  Peru: "Перу",
  Pink: "Розовый",
  Plum: "Слива",
  PowderBlue: "Пудровый Синий",
  Purple: "Фиолетовый",
  Red: "Красный",
  RosyBrown: "Розовый Коричневый",
  RoyalBlue: "Королевский Синий",
  SaddleBrown: "Седло Коричневый",
  Salmon: "Лосось",
  SandyBrown: "Песочно-Коричневый",
  SeaGreen: "Морской Зелёный",
  SeaShell: "Морская Ракушка",
  Sienna: "Сиена",
  Silver: "Серебряный",
  SkyBlue: "Небесно-Синий",
  SlateBlue: "Сланцевый Синий",
  SlateGray: "Сланцевый Серый",
  Snow: "Снег",
  SpringGreen: "Весенний Зелёный",
  SteelBlue: "Стальной Синий",
  Tan: "Загорелый",
  Teal: "Темно-Бирюзовый",
  Thistle: "Чертополох",
  Tomato: "Томат",
  Turquoise: "Бирюзовый",
  Violet: "Фиолетовый",
  Wheat: "Пшеница",
  White: "Белый",
  WhiteSmoke: "Белый Дым",
  Yellow: "Жёлтый",
  YellowGreen: "Жёлто-Зелёный",
};
